// vue-mvvm/src/components/Main.vue
<template>
  <section class="main">
    <input class="toggle-all" id="toggle-all" type="checkbox" />
    <label htmlFor="toggle-all">Mark all as complete</label>
    <ul class="todo-list" v-for="todo in todos" :key="todo.id">
      <li>
        <div class="view">
        <input class="toggle" type="checkbox" :checked="todo.completed" @click="toggleItem(todo.id)" />
        <label>{{ todo.title }}</label>
        <button class="destroy"></button>
        </div>
        <input class="edit" :value="todo.title"/>
      </li>
    </ul>
  </section>
</template>

<script>
export default {
  props: {
    todos: Array
  },
  methods: {
    toggleItem: function(id) {
      this.$emit('toggleItem', id)
    }
  }
}
</script>

// react-mvvm/todos/components/Main.jsx
import React, { useContext } from 'react';
import AppContext from '../context';

export default () => {
  const { todos, todoToggle } = useContext(AppContext)

  return <section className="main">
    <input className="toggle-all" id="toggle-all" type="checkbox" />
    <label htmlFor="toggle-all">Mark all as complete</label>
    <ul className="todo-list">
      {
        todos.map(({ title, completed, id }) => {
          return <li key={id}>
            <div className="view">
            <input className="toggle" type="checkbox" checked={completed} onChange={todoToggle.bind(null, id)}/>
            <label>{ title }</label>
            <button className="destroy"></button>
            </div>
            <input className="edit" value={title} onChange={() => {}} />
          </li>
        })
      }
    </ul>
  </section>;
}
