// vue-mvvm/src/components/Stats.vue
<template>
  <footer class="footer">
    <span class="todo-count"><strong>{{ remaining }} </strong>{{ remaining === 1 ? 'item' : 'items' }} left</span>
      <ul class="filters">
        <li>
          <a class="selected" href="#/">All</a>
        </li>
        <li>
          <a href="#/active">Active</a>
        </li>
        <li>
          <a href="#/completed">Compeleted</a>
        </li>
      </ul>
      <button class="clear-completed" v-if="completed">Clear completed</button>
  </footer>
</template>

<script>
export default {
  props: {
    todos: Array
  },
  computed: {
    remaining: function() {
      return this.todos.filter((todo) => !todo.completed).length;
    },
    completed: function() {
      return this.todos.some(todo => todo.completed)
    }
  }
}
</script>

// react-mvvm/todos/components/Stats.jsx
import React, { Component } from 'react';

export default (props) => {
  const { completed, remaining } = props;
  return <footer className="footer">
    <span className="todo-count"><strong>{ remaining }</strong>{ remaining === 1 ? 'item' : 'items' } left</span>
      <ul className="filters">
        <li>
          <a className="selected" href="#/">All</a>
        </li>
        <li>
          <a href="#/active">Active</a>
        </li>
        <li>
          <a href="#/completed">Compeleted</a>
        </li>
      </ul>
      { completed && <button className="clear-completed">Clear completed</button>}
  </footer>
}
